In [1]:
import numpy as np
import pandas as pd

In [ ]:
##DATA LOADING

In [2]:
df=pd.read_csv('training_frame.csv')

In [ ]:
##Understanding data

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   Unnamed: 0                    100000 non-null  int64  
 1   vitals_datetime               100000 non-null  object 
 2   heart_rate                    100000 non-null  float64
 3   respiration_over_impedence    100000 non-null  float64
 4   spirometry_oxygen_saturation  100000 non-null  float64
 5   pulse                         100000 non-null  float64
 6   blood_pressure_systolic       100000 non-null  float64
 7   blood_pressure_diastolic      100000 non-null  float64
 8   blood_pressure_average        100000 non-null  float64
 9   patient_id                    100000 non-null  int64  
 10  machine_id                    100000 non-null  object 
 11  Coded                         100000 non-null  float64
dtypes: float64(8), int64(2), object(2)
memory usa

In [4]:
df.describe()

Unnamed: 0     heart_rate  respiration_over_impedence  \
count  100000.000000  100000.000000               100000.000000   
mean    49999.500000      94.145950                   20.613890   
std     28867.657797      24.649687                   35.864277   
min         0.000000       0.000000                -7499.000000   
25%     24999.750000      75.000000                   15.000000   
50%     49999.500000      92.000000                   20.000000   
75%     74999.250000     108.000000                   25.000000   
max     99999.000000     233.000000                  150.000000   

       spirometry_oxygen_saturation          pulse  blood_pressure_systolic  \
count                   100000.0000  100000.000000            100000.000000   
mean                        96.7810      91.112420               128.516980   
std                          4.5127      19.871738                25.759159   
min                         12.0000      33.000000                29.000000   
25%                         96.0000      75.000000               109.000000   
50%                         98.0000      91.000000               129.000000   
75%                        100.0000     104.000000               147.000000   
max                        100.0000     292.000000               261.000000   

       blood_pressure_diastolic  blood_pressure_average    patient_id  \
count             100000.000000           100000.000000  1.000000e+05   
mean                  73.670880               90.769060  1.291026e+06   
std                   16.166517               19.286323  5.419573e+05   
min                   13.000000               15.000000  1.679400e+04   
25%                   62.000000               77.000000  1.140714e+06   
50%                   73.000000               89.000000  1.353516e+06   
75%                   83.000000              103.000000  1.816965e+06   
max                  267.000000              279.000000  9.038929e+06   

              Coded  
count  100000.00000  
mean        0.30000  
std         0.45826  
min         0.00000  
25%         0.00000  
50%         0.00000  
75%         1.00000  
max         1.00000

In [5]:
df.head()

Unnamed: 0            vitals_datetime  heart_rate  \
0           0  2020-03-28 23:00:25+00:00       111.0   
1           1  2020-03-28 23:01:10+00:00        85.0   
2           2  2020-03-28 23:30:29+00:00        92.0   
3           3  2020-03-28 23:30:29+00:00        64.0   
4           4  2020-03-28 23:30:32+00:00       111.0   

   respiration_over_impedence  spirometry_oxygen_saturation  pulse  \
0                        44.0                         100.0  110.0   
1                        12.0                          97.0   92.0   
2                         6.0                          99.0   92.0   
3                        22.0                          96.0   65.0   
4                        22.0                          96.0  102.0   

   blood_pressure_systolic  blood_pressure_diastolic  blood_pressure_average  \
0                    111.0                      74.0                    79.0   
1                     95.0                      60.0                    77.0   
2                    113.0                      71.0                    93.0   
3                    128.0                      80.0                    88.0   
4                    100.0                      64.0                    72.0   

   patient_id machine_id  Coded  
0     1585133    MICU-11    0.0  
1     1406566   BAY13-BZ    0.0  
2     1360999    SICU-09    0.0  
3      276287     NSU-03    0.0  
4     1267452    MICU-04    0.0

In [6]:
num_col=df.select_dtypes(include=np.number).columns
print('numerical columns:\n',num_col)

cat_col=df.select_dtypes(exclude=np.number).columns
print("categorical columns:\n",cat_col)

numerical columns:
 Index(['Unnamed: 0', 'heart_rate', 'respiration_over_impedence',
       'spirometry_oxygen_saturation', 'pulse', 'blood_pressure_systolic',
       'blood_pressure_diastolic', 'blood_pressure_average', 'patient_id',
       'Coded'],
      dtype='object')
categorical columns:
 Index(['vitals_datetime', 'machine_id'], dtype='object')


In [7]:
df['machine_id'].unique()

array(['MICU-11', 'BAY13-BZ', 'SICU-09', 'NSU-03', 'MICU-04', 'NSU-02',
       'NSU-01', 'NSU-06', 'MICU-03', 'MICU-09', 'MICU-02', 'SICU-07',
       'BAY22-BZ', 'MICU-05', 'MICU-07', 'MICU-01', 'SICU-02', '6WNTX-23',
       'BAY16', 'SICU-12', 'SICU-08', 'SICU-11', 'SICU-03', 'MICU-12',
       'NSU-05', '6WNTX-22', 'MICU-06', 'MICU-08', 'BAY17-BZ', '6WNTX-02',
       'MICU-10', 'SICU-10', '9B-TELE21', '6BNTX-01', 'BAY7-BZ',
       'BAY12-BZ', 'BAY14-BZ', 'BAY-8', 'BAY3-BZ', 'BAY5-BZ', '9B-TELE16',
       'SICU-6', 'SICU-5', '6WNTX-14', 'NSU-04', 'BAY19-BZ', 'BAY26-BZ',
       '9B-TELE23', 'BAY10-BZ', 'BAY4-BZ', 'BAY27-BZ', 'ISOLATION',
       '6WTELE-03', '6WTELE-09', '9B-TEL02', 'BAY42-GZ', '6BTELE-21',
       '6BTELE-23', '9B-TELE15', '6WTELE-01', '6WTELE-04', 'BAY18-BZ',
       '9B-TELE25', 'SICU-4', '9BNTX-9094', '6BTELE-17', 'SICU-04',
       'SICU-01', '9BNTX-9114', '6BTELE-05', '9B-TELE24', '6BTELE-13',
       '6WNTX-10', 'BAY25-BZ', 'BAY40-GZ', 'BAY37-GZ', '6WTELE-11',
       

In [ ]:
##Machine_id dtype is object so converting it to integer

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['machine_id'] = le.fit_transform(df['machine_id'])
df.head()

Unnamed: 0            vitals_datetime  heart_rate  \
0           0  2020-03-28 23:00:25+00:00       111.0   
1           1  2020-03-28 23:01:10+00:00        85.0   
2           2  2020-03-28 23:30:29+00:00        92.0   
3           3  2020-03-28 23:30:29+00:00        64.0   
4           4  2020-03-28 23:30:32+00:00       111.0   

   respiration_over_impedence  spirometry_oxygen_saturation  pulse  \
0                        44.0                         100.0  110.0   
1                        12.0                          97.0   92.0   
2                         6.0                          99.0   92.0   
3                        22.0                          96.0   65.0   
4                        22.0                          96.0  102.0   

   blood_pressure_systolic  blood_pressure_diastolic  blood_pressure_average  \
0                    111.0                      74.0                    79.0   
1                     95.0                      60.0                    77.0   
2                    113.0                      71.0                    93.0   
3                    128.0                      80.0                    88.0   
4                    100.0                      64.0                    72.0   

   patient_id  machine_id  Coded  
0     1585133          88    0.0  
1     1406566          53    0.0  
2     1360999         102    0.0  
3      276287          92    0.0  
4     1267452          81    0.0

In [9]:
print(df.isna().sum())

Unnamed: 0                      0
vitals_datetime                 0
heart_rate                      0
respiration_over_impedence      0
spirometry_oxygen_saturation    0
pulse                           0
blood_pressure_systolic         0
blood_pressure_diastolic        0
blood_pressure_average          0
patient_id                      0
machine_id                      0
Coded                           0
dtype: int64


In [10]:
#finding all patients id
upatient = list(df['patient_id'].unique())
upatient

[1585133,
 1406566,
 1360999,
 276287,
 1267452,
 1817092,
 1518196,
 373458,
 1129477,
 1165342,
 1679429,
 1817123,
 1817369,
 1585887,
 1816730,
 1140714,
 1817093,
 1221632,
 1799239,
 1617352,
 166375,
 473269,
 1816965,
 141258,
 1670940,
 440493,
 275356,
 1469185,
 1817430,
 1514744,
 1817126,
 1127845,
 1545046,
 1665615,
 1813087,
 1689762,
 1817502,
 1160991,
 1816827,
 1817556,
 1817558,
 1568087,
 53025,
 1816263,
 1817573,
 1204133,
 1816497,
 1817599,
 1456392,
 354424,
 1817613,
 1817650,
 1817703,
 1817711,
 1221957,
 1610043,
 1817644,
 1817710,
 1817666,
 1080756,
 157664,
 1473888,
 1817772,
 1216245,
 50380,
 1783294,
 523926,
 1300698,
 1817641,
 1817885,
 1582529,
 1817896,
 454551,
 1552101,
 1817945,
 1486377,
 1817794,
 1667528,
 1498751,
 1688566,
 50860,
 1817996,
 1598274,
 1818064,
 1586188,
 1817642,
 250120,
 1818083,
 1650826,
 1017082,
 1818047,
 1594261,
 1789715,
 80044,
 1659815,
 1675629,
 108155,
 352361,
 1818151,
 1693094,
 1603451,
 1818119,
 1

In [11]:
len(upatient)

276

In [12]:
#converting date-time to date only
date=df['vitals_datetime']
date1 = []
for x in date:
    x = str(x)
    x= x[0:10]
    date1.append(x)
date1

['2020-03-28',
 '2020-03-28',
 '2020-03-28',
 '2020-03-28',
 '2020-03-28',
 '2020-03-28',
 '2020-03-28',
 '2020-03-28',
 '2020-03-28',
 '2020-03-28',
 '2020-03-28',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-29',
 '2020-03-

In [13]:
df = df.drop(["vitals_datetime"], axis=1,inplace=False)
df.head()

Unnamed: 0  heart_rate  respiration_over_impedence  \
0           0       111.0                        44.0   
1           1        85.0                        12.0   
2           2        92.0                         6.0   
3           3        64.0                        22.0   
4           4       111.0                        22.0   

   spirometry_oxygen_saturation  pulse  blood_pressure_systolic  \
0                         100.0  110.0                    111.0   
1                          97.0   92.0                     95.0   
2                          99.0   92.0                    113.0   
3                          96.0   65.0                    128.0   
4                          96.0  102.0                    100.0   

   blood_pressure_diastolic  blood_pressure_average  patient_id  machine_id  \
0                      74.0                    79.0     1585133          88   
1                      60.0                    77.0     1406566          53   
2                      71.0                    93.0     1360999         102   
3                      80.0                    88.0      276287          92   
4                      64.0                    72.0     1267452          81   

   Coded  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0

In [14]:
df1 = pd.DataFrame(date1,columns=['date'])
df1.head()

date
0  2020-03-28
1  2020-03-28
2  2020-03-28
3  2020-03-28
4  2020-03-28

In [15]:
df = pd.concat([df1,df], axis=1)
df.head()

date  Unnamed: 0  heart_rate  respiration_over_impedence  \
0  2020-03-28           0       111.0                        44.0   
1  2020-03-28           1        85.0                        12.0   
2  2020-03-28           2        92.0                         6.0   
3  2020-03-28           3        64.0                        22.0   
4  2020-03-28           4       111.0                        22.0   

   spirometry_oxygen_saturation  pulse  blood_pressure_systolic  \
0                         100.0  110.0                    111.0   
1                          97.0   92.0                     95.0   
2                          99.0   92.0                    113.0   
3                          96.0   65.0                    128.0   
4                          96.0  102.0                    100.0   

   blood_pressure_diastolic  blood_pressure_average  patient_id  machine_id  \
0                      74.0                    79.0     1585133          88   
1                      60.0                    77.0     1406566          53   
2                      71.0                    93.0     1360999         102   
3                      80.0                    88.0      276287          92   
4                      64.0                    72.0     1267452          81   

   Coded  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0

In [16]:
df = df.drop(["Unnamed: 0"], axis=1,inplace=False)
df.head()

date  heart_rate  respiration_over_impedence  \
0  2020-03-28       111.0                        44.0   
1  2020-03-28        85.0                        12.0   
2  2020-03-28        92.0                         6.0   
3  2020-03-28        64.0                        22.0   
4  2020-03-28       111.0                        22.0   

   spirometry_oxygen_saturation  pulse  blood_pressure_systolic  \
0                         100.0  110.0                    111.0   
1                          97.0   92.0                     95.0   
2                          99.0   92.0                    113.0   
3                          96.0   65.0                    128.0   
4                          96.0  102.0                    100.0   

   blood_pressure_diastolic  blood_pressure_average  patient_id  machine_id  \
0                      74.0                    79.0     1585133          88   
1                      60.0                    77.0     1406566          53   
2                      71.0                    93.0     1360999         102   
3                      80.0                    88.0      276287          92   
4                      64.0                    72.0     1267452          81   

   Coded  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0

In [17]:
#finding all unique dates
udate = list(df['date'].unique())
udate

['2020-03-28',
 '2020-03-29',
 '2020-03-30',
 '2020-03-31',
 '2020-04-01',
 '2020-04-02',
 '2020-04-03',
 '2020-04-04',
 '2020-04-05',
 '2020-04-06',
 '2020-04-07',
 '2020-04-08',
 '2020-04-09',
 '2020-04-10',
 '2020-04-11',
 '2020-04-12',
 '2020-04-13',
 '2020-04-14',
 '2020-04-15',
 '2020-04-16',
 '2020-04-17',
 '2020-04-18',
 '2020-04-19',
 '2020-04-25',
 '2020-04-26',
 '2020-04-27',
 '2020-05-16',
 '2020-05-17',
 '2020-05-18',
 '2020-05-19',
 '2020-05-20',
 '2020-05-21',
 '2020-05-22',
 '2020-05-23',
 '2020-05-24',
 '2020-05-25',
 '2020-05-26',
 '2020-05-27',
 '2020-05-28']

In [18]:
#Finding a High-Risk event i.e. if there is atleast one "Coded=1" for any particular patient on a day
count = 0;
hrdate=[]
pid=[]
for y in upatient:
    l=[]
    for i in range(len(df)):
        if df['patient_id'][i]==y:
            l.append([df['date'][i],df["Coded"][i]])
    a=[]
    b=[]
    for x in l:
        if x[1]==1:
            a.append(x[0])
    b.append(y)
    count=count+1
    print(count)
    if list(set(a))!=[]:
        print("patient_id =",list(set(b)),"is on high risk on",list(set(a)))
    else:
        print("patient_id =",list(set(b)),"is never on high risk")
    hrdate.append(list(set(a)))
    pid.append((set(b)))

1
patient_id = [1585133] is on high risk on ['2020-04-02']
2
patient_id = [1406566] is never on high risk
3
patient_id = [1360999] is on high risk on ['2020-04-12']
4
patient_id = [276287] is on high risk on ['2020-04-09', '2020-04-07']
5
patient_id = [1267452] is on high risk on ['2020-04-01', '2020-03-29']
6
patient_id = [1817092] is never on high risk
7
patient_id = [1518196] is never on high risk
8
patient_id = [373458] is on high risk on ['2020-04-09', '2020-04-04']
9
patient_id = [1129477] is never on high risk
10
patient_id = [1165342] is on high risk on ['2020-04-26']
11
patient_id = [1679429] is on high risk on ['2020-04-04', '2020-04-17']
12
patient_id = [1817123] is on high risk on ['2020-04-06', '2020-04-01']
13
patient_id = [1817369] is never on high risk
14
patient_id = [1585887] is on high risk on ['2020-04-01']
15
patient_id = [1816730] is on high risk on ['2020-04-13']
16
patient_id = [1140714] is on high risk on ['2020-04-06', '2020-04-04']
17
patient_id = [1817093] i

141
patient_id = [187665] is never on high risk
142
patient_id = [1085969] is on high risk on ['2020-04-27']
143
patient_id = [1818621] is never on high risk
144
patient_id = [9038929] is never on high risk
145
patient_id = [1818646] is never on high risk
146
patient_id = [318772] is never on high risk
147
patient_id = [1305853] is never on high risk
148
patient_id = [1818631] is never on high risk
149
patient_id = [142527] is never on high risk
150
patient_id = [1800529] is never on high risk
151
patient_id = [1423913] is on high risk on ['2020-05-27', '2020-05-25']
152
patient_id = [471498] is never on high risk
153
patient_id = [1287607] is on high risk on ['2020-05-21', '2020-05-23']
154
patient_id = [1751806] is on high risk on ['2020-05-17', '2020-05-18']
155
patient_id = [160833] is on high risk on ['2020-05-21']
156
patient_id = [1403224] is on high risk on ['2020-05-23']
157
patient_id = [1307422] is never on high risk
158
patient_id = [1819286] is on high risk on ['2020-05-19

In [24]:
h=pd.DataFrame()
for i in range(len(hrdate)):
    list=hrdate[i]
    if list==[]:
        list=['Never on high risk']
        h=pd.concat([pd.DataFrame([[list]],columns=['Date']),h])
    else:
        h=pd.concat([pd.DataFrame([[list]],columns=['Date']),h])
    
h.head()

Date
0  [2020-05-28]
0  [2020-05-27]
0  [2020-05-25]
0  [2020-05-25]
0  [2020-05-21]

In [20]:
df2 = pd.DataFrame(pid,columns=['patient_id'])
df2

patient_id
0       1585133
1       1406566
2       1360999
3        276287
4       1267452
..          ...
271      197689
272     1756539
273     1576551
274     1810041
275     1622053

[276 rows x 1 columns]

In [25]:
h.reset_index(drop=True, inplace=True)
df2.reset_index(drop=True, inplace=True)

h = pd.concat([df2,h],axis=1)
h.head()

patient_id          Date
0     1585133  [2020-05-28]
1     1406566  [2020-05-27]
2     1360999  [2020-05-25]
3      276287  [2020-05-25]
4     1267452  [2020-05-21]

In [26]:
h['High Risk Date'] = [','.join(map(str, l)) for l in h['Date']]
h.head()

patient_id          Date High Risk Date
0     1585133  [2020-05-28]     2020-05-28
1     1406566  [2020-05-27]     2020-05-27
2     1360999  [2020-05-25]     2020-05-25
3      276287  [2020-05-25]     2020-05-25
4     1267452  [2020-05-21]     2020-05-21

In [27]:
h = h.drop(["Date"], axis=1,inplace=False)
h.head()

patient_id High Risk Date
0     1585133     2020-05-28
1     1406566     2020-05-27
2     1360999     2020-05-25
3      276287     2020-05-25
4     1267452     2020-05-21

In [28]:
#Final file of High-Risk event i.e. if there is atleast one "Coded=1" for any particular patient and on what day
h.to_csv(r'High_Risk.csv', index = False)

In [ ]:
###### MODEL Training

In [29]:
#Import models from scikit learn module:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold   #For K-fold cross validation
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import metrics

#Generic function for making a classification model and accessing performance:
def classification_model(model, data, predictors, outcome):
      model.fit(data[predictors],data[outcome])
      predictions = model.predict(data[predictors])
      print(predictions)
      accuracy = metrics.accuracy_score(predictions,data[outcome])
      print(accuracy*100)

In [62]:
#logistic Regression
outcome_var=['Coded']
predictor_var = ['heart_rate', 'respiration_over_impedence','spirometry_oxygen_saturation', 'pulse', 'blood_pressure_systolic','blood_pressure_diastolic', 'blood_pressure_average','machine_id']
model =LogisticRegression()
classification_model(model, df,predictor_var,outcome_var)

C:\Users\Mandeep Jaglan\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[0. 0. 0. ... 0. 0. 0.]
70.099


In [65]:
#Gaussian NAive bayes algorithm
from sklearn.naive_bayes import GaussianNB
outcome_var=['Coded']
predictor_var = ['heart_rate', 'respiration_over_impedence','spirometry_oxygen_saturation', 'pulse', 'blood_pressure_systolic','blood_pressure_diastolic', 'blood_pressure_average','machine_id']
model = GaussianNB() 
classification_model(model, df,predictor_var,outcome_var)

[0. 0. 0. ... 1. 1. 0.]
69.388


C:\Users\Mandeep Jaglan\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [68]:
#applying knn algorithm
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)
classification_model(model, df,predictor_var,outcome_var)

<ipython-input-29-5a599cd5ddb8>:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  model.fit(data[predictors],data[outcome])


[0. 0. 0. ... 1. 1. 1.]
94.068


In [71]:
#Gradient boost algorithm
from sklearn.ensemble import GradientBoostingClassifier
model= GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=0)
classification_model(model, df,predictor_var,outcome_var)

C:\Users\Mandeep Jaglan\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[0. 0. 0. ... 1. 1. 0.]
84.436


In [74]:
#Decision tree algorithm
from sklearn import tree
model = tree.DecisionTreeClassifier(criterion='entropy')
classification_model(model, df,predictor_var,outcome_var)

[0. 0. 0. ... 1. 1. 1.]
97.76


In [77]:
#Random forest classifier
model = RandomForestClassifier()
classification_model(model, df,predictor_var,outcome_var)

<ipython-input-29-5a599cd5ddb8>:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(data[predictors],data[outcome])


[0. 0. 0. ... 1. 1. 1.]
97.76


In [37]:
#Loading Data
test=pd.read_csv("test_frame.csv")
test.head()

Unnamed: 0            vitals_datetime  heart_rate  \
0           0  2020-08-01 00:00:01+00:00        87.0   
1           1  2020-08-01 00:00:06+00:00        49.0   
2           2  2020-08-01 00:00:14+00:00       105.0   
3           3  2020-08-01 00:00:23+00:00        82.0   
4           4  2020-08-01 00:00:32+00:00        84.0   

   respiration_over_impedence  spirometry_oxygen_saturation  pulse  \
0                        11.0                          99.0  113.0   
1                         0.0                         100.0   71.0   
2                        20.0                          95.0  106.0   
3                        23.0                         100.0   82.0   
4                        18.0                          99.0   84.0   

   blood_pressure_systolic  blood_pressure_diastolic  blood_pressure_average  \
0                    127.0                      55.0                    75.0   
1                    139.0                      65.0                   112.0   
2                     86.0                      35.0                    49.0   
3                    187.0                     112.0                   141.0   
4                    124.0                      75.0                    91.0   

   patient_id machine_id  Coded  
0     1824098  6BTELE-31    0.0  
1      151310   6WNTX-16    0.0  
2     1823860    MICU-02    0.0  
3     1824302    MICU-06    0.0  
4      131903    MICU-05    0.0

In [38]:
#Converting machine_id to int
test['machine_id'] = le.fit_transform(test['machine_id'])
test.head()

Unnamed: 0            vitals_datetime  heart_rate  \
0           0  2020-08-01 00:00:01+00:00        87.0   
1           1  2020-08-01 00:00:06+00:00        49.0   
2           2  2020-08-01 00:00:14+00:00       105.0   
3           3  2020-08-01 00:00:23+00:00        82.0   
4           4  2020-08-01 00:00:32+00:00        84.0   

   respiration_over_impedence  spirometry_oxygen_saturation  pulse  \
0                        11.0                          99.0  113.0   
1                         0.0                         100.0   71.0   
2                        20.0                          95.0  106.0   
3                        23.0                         100.0   82.0   
4                        18.0                          99.0   84.0   

   blood_pressure_systolic  blood_pressure_diastolic  blood_pressure_average  \
0                    127.0                      55.0                    75.0   
1                    139.0                      65.0                   112.0   
2                     86.0                      35.0                    49.0   
3                    187.0                     112.0                   141.0   
4                    124.0                      75.0                    91.0   

   patient_id  machine_id  Coded  
0     1824098          14    0.0  
1      151310          21    0.0  
2     1823860          61    0.0  
3     1824302          65    0.0  
4      131903          64    0.0

In [39]:
#outcome variable
y=test['Coded']
y

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
99995    1.0
99996    1.0
99997    1.0
99998    1.0
99999    1.0
Name: Coded, Length: 100000, dtype: float64

In [88]:
#prediction variable
x = test.drop(["vitals_datetime","patient_id","Coded","Unnamed: 0"], axis=1,inplace=False)
x.head()

heart_rate  respiration_over_impedence  spirometry_oxygen_saturation  \
0        87.0                        11.0                          99.0   
1        49.0                         0.0                         100.0   
2       105.0                        20.0                          95.0   
3        82.0                        23.0                         100.0   
4        84.0                        18.0                          99.0   

   pulse  blood_pressure_systolic  blood_pressure_diastolic  \
0  113.0                    127.0                      55.0   
1   71.0                    139.0                      65.0   
2  106.0                     86.0                      35.0   
3   82.0                    187.0                     112.0   
4   84.0                    124.0                      75.0   

   blood_pressure_average  machine_id  
0                    75.0          14  
1                   112.0          21  
2                    49.0          61  
3                   141.0          65  
4                    91.0          64

In [78]:
#output of predicted model
out = model.predict(x)
out

array([0., 0., 0., ..., 0., 0., 0.])

In [79]:
#Score of model prediction
model.score(x,y)

0.69095

In [ ]:
###### Neural Network model test

In [80]:
#Loading and processing training data
training_data=pd.read_csv('training_frame.csv')
training_data = training_data.drop(["Unnamed: 0","vitals_datetime","patient_id","machine_id"], axis=1,inplace=False)
training_data.head()

heart_rate  respiration_over_impedence  spirometry_oxygen_saturation  \
0       111.0                        44.0                         100.0   
1        85.0                        12.0                          97.0   
2        92.0                         6.0                          99.0   
3        64.0                        22.0                          96.0   
4       111.0                        22.0                          96.0   

   pulse  blood_pressure_systolic  blood_pressure_diastolic  \
0  110.0                    111.0                      74.0   
1   92.0                     95.0                      60.0   
2   92.0                    113.0                      71.0   
3   65.0                    128.0                      80.0   
4  102.0                    100.0                      64.0   

   blood_pressure_average  Coded  
0                    79.0    0.0  
1                    77.0    0.0  
2                    93.0    0.0  
3                    88.0    0.0  
4                    72.0    0.0

In [81]:
#allocating training data
X_train = training_data.iloc[:, 0:7]
y_train = training_data.iloc[:, 7:8]

In [82]:
#Loading and processing test data
newdata=pd.read_csv('test_frame.csv')
newdata = newdata.drop(["Unnamed: 0","vitals_datetime","patient_id","machine_id"], axis=1,inplace=False)
newdata.head()

heart_rate  respiration_over_impedence  spirometry_oxygen_saturation  \
0        87.0                        11.0                          99.0   
1        49.0                         0.0                         100.0   
2       105.0                        20.0                          95.0   
3        82.0                        23.0                         100.0   
4        84.0                        18.0                          99.0   

   pulse  blood_pressure_systolic  blood_pressure_diastolic  \
0  113.0                    127.0                      55.0   
1   71.0                    139.0                      65.0   
2  106.0                     86.0                      35.0   
3   82.0                    187.0                     112.0   
4   84.0                    124.0                      75.0   

   blood_pressure_average  Coded  
0                    75.0    0.0  
1                   112.0    0.0  
2                    49.0    0.0  
3                   141.0    0.0  
4                    91.0    0.0

In [83]:
#allocating test data
X_test = newdata.iloc[:, 0:7]
y_test = newdata.iloc[:, 7:8]

In [84]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [85]:
#Neural Network Model Training
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

In [86]:
#predictions of Neural Network data
predictions = mlp.predict(X_test)

In [87]:
#Evaluating the model
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[58637 11363]
 [23237  6763]]
              precision    recall  f1-score   support

         0.0       0.72      0.84      0.77     70000
         1.0       0.37      0.23      0.28     30000

    accuracy                           0.65    100000
   macro avg       0.54      0.53      0.53    100000
weighted avg       0.61      0.65      0.62    100000



In [1]:
#####FINAL REPORT
#
# We made a High_Risk.csv file which show which pateint is on high risk on which day
#
# Second, we made different models and chose the best one to detemine code-blue risk using their acuuracies
#
#
#   Model/Algorithm                   Training data accuracy        Test data accuracy
#
#  Linear Regression                            70%                       69.989%
#  Naive Bias                                   69.388%                   67.544%
#  KNN Algorithm                                94.068%                   59.532%
#  Gradient Boost                               84.436%                   66.38%
#  Decision Tree                                97.76%                    58.265%
#  Random Forest                                97.76%                    69.095%
#  Neural Network                                                         77%


#So, we will use Neural-Network as it provides bes accuracy for our test data. Next choice would be Random Forest.